[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ttt = "42YULYY5TyFnGhNpVb45NN78mXebbGXoy31NJQukjLHo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gizem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
